name: E2E (Playwright)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      E2E_BASE_URL: ${{ vars.E2E_BASE_URL }}
      E2E_PRODUCT_URL: ${{ vars.E2E_PRODUCT_URL }}
      TZ: America/Santiago

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers & deps
        run: npx playwright install --with-deps

      - name: Run Playwright tests (1 worker, html+github reporters)
        run: npx playwright test --workers=1 --reporter=github,html

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_number }}
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload raw test-results (traces/videos/screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: test-results
          if-no-files-found: ignore
          retention-days: 7
